"""empty message

Revision ID: 1d80c235f20a
Revises: 830387ae7b45
Create Date: 2022-09-01 18:00:07.329809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d80c235f20a'
down_revision = '830387ae7b45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('genre', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'genre')
    # ### end Alembic commands ###
