"""empty message

Revision ID: 821035629294
Revises: e139b6e56ea6
Create Date: 2022-09-16 17:37:13.758022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '821035629294'
down_revision = 'e139b6e56ea6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('picture', sa.String(length=240), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'picture')
    # ### end Alembic commands ###
