"""empty message

Revision ID: 830387ae7b45
Revises: d8f759558d22
Create Date: 2022-08-31 17:50:40.466365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '830387ae7b45'
down_revision = 'd8f759558d22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
